obj-m:=module1.o

KDIR := /home/sasl/shared/saintbauzel/BBB/linux/build

all: default execs


default:
	$(MAKE) CROSS_COMPILE=arm-linux-gnueabihf- ARCH=arm  -C ${KDIR} SUBDIRS=$(shell pwd) modules

clean:
	rm -f *.[oas] .*.flags *.ko .*.cmd .*.d .*.tmp *.mod.c ioctl_pwm

execs: ioctl_pwm.c
	arm-linux-gnueabihf-gcc -o ioctl_pwm ioctl_pwm.c
